# Generated by Django 3.1.2 on 2020-11-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0003_auto_20201104_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('rut1', models.CharField(help_text='ingrese 8 Caracteres', max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
    ]
