# Generated by Django 3.1.2 on 2020-11-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0004_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['nombre']},
        ),
    ]
