# Generated by Django 3.1.2 on 2020-11-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0005_auto_20201125_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='recontraseña',
            new_name='equipo',
        ),
    ]
