# Generated by Django 3.1.2 on 2020-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0006_auto_20201130_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.CharField(max_length=2),
        ),
    ]
