# Generated by Django 3.1.2 on 2020-11-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0007_auto_20201130_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
